export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ERROR_ROUTE = '/'

export const ADMIN_MAIN_ROUTE = '/adminMain'
export const REQUESTS_ROUTE = '/requests'
export const ACCEPTED_REQUESTS_ROUTE = '/acceptedRequests'
export const APPROVED_REQUESTS_ROUTE = '/approvedRequests'
export const REJECTED_REQUESTS_ROUTE = '/rejectedRequests'
export const STATISTICS_ROUTE = '/statistics'
export const CLIENT_STATISTICS_ROUTE = '/clientStatistics'
export const DONATION_STATISTICS_ROUTE = '/donationStatistics'

export const ALL_CATS_ROUTE = '/allCats'
export const ALL_DOGS_ROUTE = '/allDogs'
export const HOME_ROUTE = '/home'
export const PERSONAL_CABINET_ROUTE = '/personalCabinet'
export const TAKE_PET_ROUTE = '/takePet'
export const GIVE_PET_ROUTE = '/givePet'
export const DONATION_ROUTE = '/donation'