export const LOGIN_ROUTE = '/user/login'
export const REGISTRATION_ROUTE = '/client/registration'
export const ERROR_ROUTE = '/'

export const ADMIN_MAIN_ROUTE = '/adminMain'
export const REQUESTS_ROUTE = '/requests'
export const ACCEPTED_REQUESTS_ROUTE = '/request/getAccepted'
export const APPROVED_REQUESTS_ROUTE = '/request/getApproved'
export const REJECTED_REQUESTS_ROUTE = '/request/getRejected'
export const STATISTICS_ROUTE = '/statistics'
export const CLIENT_STATISTICS_ROUTE = '/client/clientStatistics'
export const DONATION_STATISTICS_ROUTE = '/donationStatistics'

export const ALL_CATS_ROUTE = '/allCats'
export const ALL_DOGS_ROUTE = '/allDogs'
export const HOME_ROUTE = '/home'
export const PERSONAL_CABINET_ROUTE = '/request/personalCabinet'
export const TAKE_CAT_ROUTE = '/pet/takeCat' 
export const TAKE_DOG_ROUTE = '/pet/takeDog'
export const GIVE_PET_ROUTE = '/request/givePet'
export const DONATION_ROUTE = '/donation/addDonation'